Adição do endpoint de cadastro (POST) de Tecnico
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #2
Opened 2022-03-11 00:24 UTC by thiagohdaqw

## Descrição

Adição do endpoint de criação de tecnicos

## Está consertando alguma issue aberta?

[#10](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/105)

## Tarefas gerais realizadas
- Adição da model de tecnico
- Adição da view e serializer para POST de tecnico
- Adição de tipos básicos do backend (CREA)
- Adição de classes bases para  testes de usuario
- Adição de testes de cadastro de técnico

2022-03-11 00:33 UTC, thiagohdaqw commented
# Como testar 

- ### Se for a primeira vez que estiver excutando o backend, siga os seguintes comandos na pasta raiz: `docker-compose up`
![image](https://user-images.githubusercontent.com/54081877/157352518-8029180a-7cbe-41ab-a541-f7e81bf3b1a3.png)


<hr>

- ### Em outro terminal, entre no shell do docker: `docker-compose exec caderneta_digital bash`

![image](https://user-images.githubusercontent.com/54081877/157352625-a56ad057-9aa2-4229-8e6a-a316a0d53892.png)


<hr>

- ### Rode as migrações: `python manage.py migrate`

![image](https://user-images.githubusercontent.com/54081877/157352671-6d798fb8-65ca-42a7-b024-d56beba7ed81.png)


<hr>

- ### Pronto agora é só acessar a rota `http://127.0.0.1:8000/api/produtor/` e testar

![image](https://user-images.githubusercontent.com/54081877/157352770-c3ba0006-dda0-42d8-bbf4-362d3bf285c3.png)

<hr>

- ### Para rodar os testes, no shell do docker, execute: `python manage.py test` ou `pytest`

2022-03-11 02:30 UTC, Joao-Moura requested changes
Show de mais galera, parabéns pelo trabalho. Só achei um errinho que não sei como ele passou no teste mas enfim kkkkk.
Outra coisa que eu queria citar é que esse teu linter é horrível em Thiago kkkkk, ele ajeita tudo no formato de C para os colchetes e parênteses. Não sei se o flake8 vai reclamar disso, mas se vc quiser eu sugiro deixar na formatação antiga.
No mais é isso, novamente parabéns pessoal.

2022-03-11 02:30 UTC, Joao-Moura commented on tecnico/tests/views/test_tecnico.py
> +            ('123456789'),
```suggestion
            ('123456789',),
```

2022-03-11 02:41 UTC, thiagohdaqw commented on tecnico/tests/views/test_tecnico.py
> +            ('123456789'),
Isso nao seria um erro. O parameterized expand interpreta as entradas nas seguintes formas:
'item'
('item',)
('item, 'mensagem')
Então não daria erro nos testes kk. Mas modificarei para manter o padrão.

2022-03-11 02:42 UTC, thiagohdaqw commented on tecnico/tests/views/test_tecnico.py
> +            ('123456789'),
Já sobre o linter, ele segue a pep8, entao acho q nao terá problemas

2022-03-11 03:05 UTC, Joao-Moura approved these changes
Show

2022-03-12 00:52 UTC, RcleydsonR approved these changes
Show de bola, excelente trabalho...
Rodei o flake8 com:
python -m flake8 . --max-line-length=254 --exclude migrations --show-source --statistics
e obtive alguns erros, mas creio que serão tratados na minha task para passar o CI...

2022-03-12 01:00 UTC, merged