Adição do endpoint de cadastro (POST) de Plantio e Cultura + melhorias
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #21
Opened 2022-03-26 00:08 UTC by Joao-Moura

## Descrição

Adição do endpoint de criação de plantio e cultura

## Está consertando alguma issue aberta?

- [#146](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/146)

## Tarefas gerais realizadas
- Adição da model de plantio
- Adição da view e serializer para POST de plantio
- Adição de testes de cadastro de plantio
- - Adição da model de cultura
- Adição da view e serializer para POST de cultura
- Adição de testes de cadastro de cultura
- Criação de arquivo de constantes no core
- Melhoria do Makefile para testes de métodos específicos

2022-03-26 00:24 UTC, Joao-Moura commented
Adições no Make para rodar testes:
```bash
# Rodando todos os testes
make test

# Rodando um arquivo de testes específico
make test FILE=seu/arquivo/aqui.py

# Rodando um teste ou classe de teste esepecífico
make test TEST=nomeDoSeuTesteOuClasse

# Forma mais eficiente do exemplo anterior (selecionando o arquivo daquele teste)
make test FILE=seu/arquivo/aqui.py TEST=nomeDoSeuTesteOuClasse
```

2022-03-27 12:17 UTC, thiagohdaqw requested changes
Bom trabalho. Tem um erro de modelagem q espefico mais abaixo

2022-03-27 12:17 UTC, thiagohdaqw commented on plantio/models/plantio.py
> +    estado = models.CharField(max_length=2, choices=UF_CHOICES)
Esse estado se refere ao estado do plantio e não do UF. 
![image](https://user-images.githubusercontent.com/54081877/160280892-1c584c84-cff5-4206-85b3-7970ed3c9e8b.png)
O estado inicial é plantado.

2022-03-28 00:24 UTC, Joao-Moura commented on plantio/models/plantio.py
> +    estado = models.CharField(max_length=2, choices=UF_CHOICES)
Foi feita uma pequena troca de PeriodoDeCarencia para apenas Carencia

2022-03-28 00:41 UTC, thiagohdaqw approved these changes
Bom trabalho

2022-03-28 00:57 UTC, merged