Adição do endpoint de visualização (GET) de propriedade
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #24
Opened 2022-03-30 21:09 UTC by RcleydsonR

## Descrição

Adição do endpoint de  visualização (GET) de propriedade

## Está consertando alguma issue aberta?

- [#154](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/154)

## Tarefas gerais realizadas
- Alteração no get_queryset de propriedade para se adequar a visualização necessária
- Alteração do generics de CreateAPIView para ListCreateAPIView
- Mudança dos choices de tipo de usuário para consts
- Adição de testes necessários

2022-03-30 21:19 UTC, Joao-Moura requested changes
Parabéns, ficou show. Apenas umas correções nos testes

2022-03-30 21:19 UTC, Joao-Moura commented on propriedade/tests/views/test_propriedade.py
> +        propriedade.make(produtor=self.produtor, tecnico=self.tecnico)
adicionar uma propriedade para outro produtor. Ex.:
```suggestion
        propriedade.make(produtor=self.produtor, tecnico=self.tecnico)
        propriedade.make(produtor=produtor.make(), tecnico=self.tecnico)
```

2022-03-30 21:19 UTC, Joao-Moura commented on propriedade/tests/views/test_propriedade.py
> +        self.assertNotEqual([], response.json())
NotEqual não é o melhor, testar se a quantidade retornada é igual a quantidade que tem no banco apenas para produtores

2022-03-30 21:19 UTC, Joao-Moura commented on propriedade/tests/views/test_propriedade.py
> +    def test_lista_propriedade_de_um_tecnico_autenticado(self):
Mesmos comentários feitos no teste anterior

2022-03-30 23:45 UTC, Joao-Moura commented on propriedade/views/propriedade.py
>      serializer_class = PropriedadeSerializer
Aqui fica uma avaliação (@thiagohdaqw depois da a sua opnião também). Não seria melhor já fazer esse serializer de detail para detalhar todas as informações da prop. ? Isso incluiria os talhões e talvez até as plantações daquela propriedade

2022-03-30 23:54 UTC, thiagohdaqw commented on propriedade/views/propriedade.py
>      serializer_class = PropriedadeSerializer
é isso ai mesmo. serializer da propriedade com os lookup dos talhoes

2022-04-01 03:07 UTC, RcleydsonR commented on propriedade/views/propriedade.py
>      serializer_class = PropriedadeSerializer
Perfeito galera, faz total sentido, fiz as alterações nececssárias !

2022-04-01 17:44 UTC, Joao-Moura approved these changes
😳

2022-04-01 19:11 UTC, thiagohdaqw requested changes
Bom trabalho, rafael. Sua evolução no backend está monstruosa. Deixa umas duvidas abaixo

2022-04-01 19:11 UTC, thiagohdaqw commented on propriedade/urls.py
> +        url(r'^(?P<pk>[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-4[0-9A-Za-z]{3}-[89ABab][0-9A-Za-z]{3}-[0-9A-Za-z]{12})/$', PropriedadeRetrieveAPIViewTest.as_view(), name='propriedade-detail'),
acho que seria bom abstrair esse regex para ser reutilizado em outras rotas.

2022-04-01 19:11 UTC, thiagohdaqw commented on propriedade/urls.py
> +        url(r'^(?P<pk>[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-4[0-9A-Za-z]{3}-[89ABab][0-9A-Za-z]{3}-[0-9A-Za-z]{12})/$', PropriedadeRetrieveAPIViewTest.as_view(), name='propriedade-detail'),
esse regex tá na norma do uuid? acho que o default não funciona nele 00000000-0000-0000-0000-000000000000 que seria valido. Além disso, as letras vão de a-f e não de a-z.

https://stackoverflow.com/a/6640851

2022-04-01 19:11 UTC, thiagohdaqw commented on propriedade/serializers/propriedade.py
> +    talhao = TalhaoSerializer(many=True, read_only=True, source='talhao_set')
Essa rota vai atender essa tela do prototipo? Se sim, deveria devolver os plantios ativos dos talhoes
![image](https://user-images.githubusercontent.com/54081877/161326728-aafe82de-068f-4b69-9942-6626fdb96592.png)

2022-04-01 19:21 UTC, Joao-Moura commented on propriedade/serializers/propriedade.py
> +    talhao = TalhaoSerializer(many=True, read_only=True, source='talhao_set')
Seria interessante, mas o request vai ficar pesadinho kkkk. Só que vendo aqui não consigo imaginar outro endpoint melhor que esse para isso

2022-04-01 19:30 UTC, RcleydsonR commented on propriedade/urls.py
> +        url(r'^(?P<pk>[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-4[0-9A-Za-z]{3}-[89ABab][0-9A-Za-z]{3}-[0-9A-Za-z]{12})/$', PropriedadeRetrieveAPIViewTest.as_view(), name='propriedade-detail'),
Obg Thiago, vou fazer os ajustes necessários, muito bem colocado, no caso desse regex, seria interessante colocar em consts correto ?

2022-04-01 19:30 UTC, RcleydsonR commented on propriedade/serializers/propriedade.py
> +    talhao = TalhaoSerializer(many=True, read_only=True, source='talhao_set')
Rapaz, vocês amaram abstrair essa task ein kkkkkkkkkkkkkkkkkkkkkkk, o pior é que estão cheios de razão ;(

2022-04-01 19:47 UTC, thiagohdaqw commented on propriedade/urls.py
> +        url(r'^(?P<pk>[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-4[0-9A-Za-z]{3}-[89ABab][0-9A-Za-z]{3}-[0-9A-Za-z]{12})/$', PropriedadeRetrieveAPIViewTest.as_view(), name='propriedade-detail'),
recomendo /consta/urls

2022-04-02 14:50 UTC, thiagohdaqw approved these changes
Bom trabalho

2022-04-02 14:50 UTC, thiagohdaqw commented on propriedade/serializers/propriedade.py
> +            context=[PLANTIO_CHOICES[0][0], PLANTIO_CHOICES[1][0], PLANTIO_CHOICES[2][0]],
Esse contexto com as escolhas dos plantio não está nada legivel. Fica a seu cargo refatorar agora para um enum ou deixar assim mesmo

2022-04-02 14:50 UTC, thiagohdaqw commented on propriedade/serializers/propriedade.py
> +            context=[PLANTIO_CHOICES[0][0], PLANTIO_CHOICES[1][0], PLANTIO_CHOICES[2][0]],
Normalmente, se usa context como um dicionario, olhando só por essa linha não dá pra entender qual seria esse contexto. No caso, assim ficaria bem mais legivel `context={"plantio_estado_filtro": [PLANTADO, COLHEITA, CARENCIA]}`

2022-04-02 14:50 UTC, thiagohdaqw commented on propriedade/tests/views/test_propriedade.py
> +        self.url = reverse_lazy(
Poderia abstrair em uma função pra facilitar a reutilização:
```
def url(idPropriedade=None):
    if idPropriedade is None:
        idPropriedade = self.propriedade.idPropriedade
    return reverse_lazy("propriedade-detail", pk=idPropriedade)```

2022-04-02 15:39 UTC, RcleydsonR commented on propriedade/tests/views/test_propriedade.py
> +        self.url = reverse_lazy(
Hm, boa sugestão, agradeço.

2022-04-02 15:40 UTC, RcleydsonR commented on propriedade/serializers/propriedade.py
> +            context=[PLANTIO_CHOICES[0][0], PLANTIO_CHOICES[1][0], PLANTIO_CHOICES[2][0]],
É pq mandando como lista facilita o uso do context por parte do serializer que recebe ele, porque não teria que traduzir o dict para uma lista, talvez o enum resolva o problema da legibilidade, mas passar como dict para depois traduzir seja um retrabalho.

2022-04-02 15:48 UTC, RcleydsonR commented on propriedade/serializers/propriedade.py
> +            context=[PLANTIO_CHOICES[0][0], PLANTIO_CHOICES[1][0], PLANTIO_CHOICES[2][0]],
Mas farei mesmo assim, facilita o entendimento

2022-04-02 16:11 UTC, merged