Adicionando endpoint PATCH/UPDATE/DETAIL para usuários
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #31
Opened 2022-04-07 00:17 UTC by Joao-Moura

## Descrição

Adicionando endpoint PATCH/UPDATE/DETAIL para usuários (produtor e técnico)

## Está consertando alguma issue aberta?

- [#166](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/166)

## Tarefas gerais realizadas
- Melhorias dos serializers
- Adição do endpoint de PATCH/UPDATE/DETAIL
- Adição de testes
- Adição de flag no Makefile para testes, retirando warnings

2022-04-07 13:54 UTC, thiagohdaqw approved these changes
Show de bola

2022-04-07 13:55 UTC, RcleydsonR requested changes
Excelente trabalho João, testes muito bem feitos, mas acredito que passou um ponto que é a validação do usuário que está fazendo update, comentei melhor abaixo!

2022-04-07 13:55 UTC, RcleydsonR commented on .codeclimate.yml
> +    enabled: false
Opa, sugiro não remover essa verificação porque podemos extrapolar alguns métodos tornando-os muito acoplados, porém pode aumentar a verificação se comparada ao default (complexidade 5), ficaria assim:
![image](https://user-images.githubusercontent.com/74625814/162209290-08bb705d-b400-4b3c-9f48-88885ef7fa97.png)

2022-04-07 13:55 UTC, RcleydsonR commented on usuario/urls.py
> +            r'^(?P<idUsuario>{})/$'.format(UUID4_URL),
Essa rota é necessária principalmente para detalhar um usuário, ex: Técnico detalha Produtor, ou vice versa, porém não encontrei a validação necessária para não deixar um técnico atualizar os dados de um produtor, ou vice versa, ou entre eles, seria interessante pegar pelo token quando fosse um PATCH ou um UPDATE.

2022-04-07 13:55 UTC, RcleydsonR commented on usuario/serializers/usuario.py
> +    def update(self, instance, validated_data):
Como comentado nas URL's, eu posso alterar os dados de qualquer um, a partir do idUsuario dele, o que é errado já que tem que ser validado se estou mudando os dados do meu próprio usuário.
![image](https://user-images.githubusercontent.com/74625814/162215584-6dd3fda3-c915-4e25-bb97-0268a9bb01d1.png)
Nessa imagem estou logado com outra conta mas consegui mudar os dados desse produtor a partir do idUsuário dele

2022-04-07 21:47 UTC, Joao-Moura commented on usuario/urls.py
> +            r'^(?P<idUsuario>{})/$'.format(UUID4_URL),
Entendo, inicialmente eu fiz toda essa api com token, porém fica inviável pois para casos onde seja necessário um técnico editar um produtor (lembro da gente ter conversado rápido sobre isso) isso necessitaria de um novo endpoint.
Em relação a um poder editar o outro, não tem muito pra onde fugir porque isso seria feito pelas permissões, ficando como dívida técnica ai pro nosso back 😥

2022-04-07 21:47 UTC, Joao-Moura commented on usuario/serializers/usuario.py
> +    def update(self, instance, validated_data):
Acredito que a resposta de cima sirva para aqui também. Vou marcar essa concluída para podermos discutir apenas em uma mensagem.

2022-04-07 23:25 UTC, RcleydsonR commented on usuario/urls.py
> +            r'^(?P<idUsuario>{})/$'.format(UUID4_URL),
A ideia do técnico editar um produtor era na nossa primeira abordagem, depois da conversa com a cliente que a gente entendeu que as maiores responsabilidades eram do produtor não faz sentido deixar o técnico editar o produtor, visto que o aplicativo é de fácil utilização para ajudar nesses casos, acho que o mais correto nesse caso é fazer por token mesmo.

2022-04-11 02:24 UTC, RcleydsonR approved these changes
Devido à explicação dada às alterações solicitadas, concordo com o que está feito, excelente trabalho!

2022-04-11 02:41 UTC, merged