Adicionando endpoint DELETE para agrotóxicos
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #34
Opened 2022-04-07 03:25 UTC by Joao-Moura

## Descrição

Adicionando endpoint DELETE para agrotóxicos

## Está consertando alguma issue aberta?

- [#168](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/168)

## Tarefas gerais realizadas
- Adição do endpoint de DELETE
- Adição de testes

2022-04-07 13:31 UTC, thiagohdaqw requested changes
Muito bom trabalho. Só encontrei um problema, quando deleta um agrotoxico com relacionamento espera com cultura
![image](https://user-images.githubusercontent.com/54081877/162210654-e6da3c74-eb84-4cfc-9f68-035e8fd17606.png)

2022-04-08 04:44 UTC, RcleydsonR approved these changes
Top demais João, só deixei um comentário como pergunta mesmo porque acabei implementando no meu PR a mensagem como 'error', mas aí teria que mudar todas as mensagens de erro da API que daria um bom trabalho kkkk, de qualquer maneira aguardo um feedback, tirando isso o endpoint está okay!

2022-04-08 04:44 UTC, RcleydsonR commented on agrotoxico/views/agrotoxico.py
> +                {'agrotoxico': 'Não é possível apagar um agrotoxico que está em tempo de espera de uma cultura.'},
Talvez a mensagem de erro aqui seria melhor 'error' para facilitar pro frontend, não? Mesma coisa acima, obviamente isso pode ser passível de discussão mesmo porque do jeito que está é como temos no padrão rest.

2022-04-08 12:42 UTC, Joao-Moura commented on agrotoxico/views/agrotoxico.py
> +                {'agrotoxico': 'Não é possível apagar um agrotoxico que está em tempo de espera de uma cultura.'},
Não acho bom. Como já foi discutido na planning, se a gente já sabe de que campo está vindo o erro o correto seria retornar no nome dele. Além disso, error não é o correto pois caso queira seguir o padrão django e django_rest deveria ser retornado num non_fields_error 🙄😫😝

2022-04-10 16:34 UTC, thiagohdaqw approved these changes

2022-04-10 16:35 UTC, merged