Adicionando endpoint DETAIL/PATCH/UPDATE para plantio
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #37
Opened 2022-04-08 04:38 UTC by RcleydsonR

## Descrição

Adicionando endpoint PATCH/UPDATE/DETAIL para plantio

## Está consertando alguma issue aberta?

- [#172](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/172)

## Tarefas gerais realizadas
- Adição do endpoint de DETAIL/PATCH/UPDATE
- Validação do talhão no serializer PlantioAPIView
- Adição de testes

2022-04-10 21:42 UTC, Joao-Moura requested changes
Correções no serializer, avaliar se são condizentes (e funcionais kkkkk). De qualquer forma, parabéns pelo trabalho.

2022-04-10 21:42 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
```suggestion
            if not Talhao.objects.filter(idTalhao=validated_data.get('talhão'), idPropriedade=instance.talhao.idPropriedade).existis():
```

2022-04-10 21:42 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Essa validação não deveria estar sendo feita em um validate da vida ? Update normalmente só tem o fluxo de atualização do objeto

2022-04-10 21:42 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +        return instance
```suggestion
        return super().update(instance, validated_data)
```

2022-04-11 02:27 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Cara, mas do jeito que está creio que se encontra muito mais legível, e como a alteração não traria benefícios de desempenho creio que não seja necessária.

2022-04-11 02:29 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Acredito que seja interessante desacoplar devido às atribuições de cada. Irei aplicar as mudanças.

2022-04-11 02:30 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +        return instance
Feshow

2022-04-11 02:33 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Na verdade, esse validate é íntriseco ao update do plantio, então não sei se ele ficaria tranquilamente em uma função de validate, qual seria o nome dela ? validate_plantio_update ? Kkkkkk

2022-04-11 02:39 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Não necessariamente. Até porque você não deveria poder criar um plantio que o talhão não seja da sua propriedade. O nome correto teria que ser em conformidade com o django_rest: `validate_talhao`

2022-04-11 02:41 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Existiria o benefício que o banco só estaria sendo acessado uma vez, e a quantidade de tuplas retornadas seria menor, logo mais eficiente

2022-04-11 02:44 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Como assim, o validated_data acessa o banco ? Se sim você estaria acessando o banco 2 vezes também... Quanto a quantidade de tuplas retornada é a mesma, pois se trata dos talhões de determinada propriedade, não é uma consulta complexa que necessite melhoria, pois o banco é acessado através da chave primária que é um índice com muito desempenho, ou seja, sem melhoria no desempenho é preferível a legibilidade, eu acho...

2022-04-11 02:46 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
O problema é que ele não vai saber qual a propriedade do produtor que está criando o plantio no momento de criação, pois só é passado o id do talhão e não tem referência nenhuma a propriedade... O caso do update é que ele pode tentar mudar o talhão do plantio para uma propriedade que não seja a dele, o que pode causar inconsistência nos dados reais, mas no banco estaria tudo bem, por a referência ser o talhão, mas a gente sabe da propriedade, pois já tem um talhão anterior que é possível ser consultado kk, sem isso não dá para fazer nada.

2022-04-11 02:47 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Realmente, não acessa duas vezes. Entretanto, a diferença entre os dois códigos é a quantidade de tuplas. No código em que o valor é salvo em memória numa variável a quantidade é muito maior que a utilizada no if, e isso pode resultar em uma diferença consideravel de desempenho

2022-04-11 02:50 UTC, Joao-Moura commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Não, pois esse serializer é de talhão, logo se assume que a propriedade está criada e foi validada corretamente. Esse caso que você citou de update cabe perfeitamente para o create, já que não deve ser possível um plantio ser criado para um talhão que não faça parte da propriedade nem virce e versa

2022-04-11 02:51 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Sim, nesse aspecto o resultado do if já está sendo retornado do banco que acaba otimizando o desempenho, farei a troca, agradeço imensamente o feedback :100:

2022-04-11 02:55 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +                raise serializers.ValidationError({'error': 'Esse talhão não pertence a propriedade onde está localizado esse plantio.'})
Mas isso já é validado no serializer de talhão kkkkkk, eu quero validar que o update não está mudando o plantio de propriedade saca, ele pode mudar de talhão desde que o talhão esteja na mesma propriedade que o do antigo.

2022-04-11 03:15 UTC, RcleydsonR commented on plantio/serializers/plantio.py
> +            if(validated_data.get('talhao') not in talhoes_validos):
Na verdade para esse caso específico não precisa de uma consulta ao banco, irei subir as alterações com a nova solução.

2022-04-11 15:20 UTC, thiagohdaqw approved these changes
🚀

2022-04-11 16:55 UTC, Joao-Moura approved these changes
😚

2022-04-11 16:55 UTC, merged