Adicionando endpoint LIST para propriedades sem técnico
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #39
Opened 2022-04-12 01:41 UTC by Joao-Moura

## Descrição

Adicionando endpoint LIST para propriedades sem técnico

## Está consertando alguma issue aberta?

- [#181](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/181)

## Tarefas gerais realizadas
- Adição do endpoint de LIST
- Adição de testes

2022-04-12 13:26 UTC, thiagohdaqw approved these changes
🚀

2022-04-12 14:45 UTC, RcleydsonR requested changes
Muito bom, coloquei só uma mudança que acho necessária na view criada, mudança bem simples que dá pra fazer rapidamente, não vamos deixar sem fazer :3

![gif](https://c.tenor.com/bfnPEuMuOFIAAAAC/naruto-yay.gif)

2022-04-12 14:45 UTC, RcleydsonR commented on propriedade/views/propriedade.py
> +    queryset = Propriedade.objects.filter(tecnico__isnull=True)
Acho que poderia ser feita uma validação estilo:
![image](https://user-images.githubusercontent.com/74625814/162988788-7cd05ba0-df49-4080-b6b4-327f6961099f.png)
Já que não faz sentido os produtores terem acesso a essas informações.

2022-04-12 14:56 UTC, Joao-Moura commented on propriedade/views/propriedade.py
> +    queryset = Propriedade.objects.filter(tecnico__isnull=True)
Não
![](https://media.discordapp.net/attachments/713447701735538740/738454959657451641/4470_Neutral_Cursed.gif)

2022-04-12 14:57 UTC, RcleydsonR commented on propriedade/views/propriedade.py
> +    queryset = Propriedade.objects.filter(tecnico__isnull=True)
Sim!!
[][][][][][][][][][][][][][][][]

2022-04-13 00:16 UTC, RcleydsonR approved these changes
Excelente! Agora está mais coerente.

![gif](https://i.giphy.com/media/GRSnxyhJnPsaQy9YLn/giphy.webp)

2022-04-13 00:50 UTC, merged