Configurando pipeline de CI/CD do backend
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #4
Opened 2022-03-11 21:26 UTC by RcleydsonR

## Descrição

Adição dos pipelines de ci/cd, makefile e qa contínuo

## Está consertando alguma issue aberta?

- [#115](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/115)

## Tarefas gerais realizadas
- Adição do makefile

2022-03-13 18:04 UTC, thiagohdaqw requested changes

2022-03-13 18:04 UTC, thiagohdaqw commented on Makefile
> +test:
Não consegui rodar o  make test sem que o container do postgres esteja ligado. É assim mesmo?

![image](https://user-images.githubusercontent.com/54081877/158072473-f6421d82-f713-4b2d-8ad9-be20380170e0.png)

2022-03-13 18:04 UTC, thiagohdaqw commented on Makefile
> +lint:
Precisa de mais alguma configuração a mais? o lint fica travado assim 
![image](https://user-images.githubusercontent.com/54081877/158072878-a66639a1-e347-4e05-a5b0-22981b458393.png)

2022-03-13 20:55 UTC, RcleydsonR commented on Makefile
> +test:
É não, o --no-deps acabava subindo somente o backend sem o container do postgres, vou retirá-lo.

2022-03-14 02:34 UTC, Joao-Moura approved these changes
Show de bola, parabéns

2022-03-14 02:50 UTC, thiagohdaqw approved these changes

2022-03-14 15:49 UTC, merged