Adicionando campo de foto na cultura
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #41
Opened 2022-04-12 13:59 UTC by thiagohdaqw

## Descrição

Adicionando campo de foto na cultura

## Está consertando alguma issue aberta?

- [#183](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/183)

## Tarefas gerais realizadas
- Adição do campo foto da cultura
- Adição de testes

2022-04-12 14:56 UTC, RcleydsonR requested changes
Excelente trabalho!!!!! Só deixei um comentário de erro ortográfico mesmo, após isso o approve vem!

![gif](https://www.icegif.com/wp-content/uploads/one-piece-icegif.gif)

2022-04-12 14:56 UTC, RcleydsonR commented on cultura/tests/views/test_cultura.py
> +    def test_nao_cria_cultura_atributos_obrigatorios(self, campo, mensage):
Esse mensage está meio errado, acho que ou é mensagem ou message kkk

2022-04-12 15:07 UTC, Joao-Moura approved these changes
Show mano, parabéns.
![](https://c.tenor.com/swKlGxmxsBwAAAAM/social-credit-denis-romavich.gif)

2022-04-13 00:20 UTC, RcleydsonR approved these changes
Tooooop!

![GIF](https://c.tenor.com/5IOe3HEeZ_cAAAAd/ivete-sangalo-sucesso.gif)

2022-04-13 00:27 UTC, merged