Adição do endpoint de DETAIL do histórico de um talhão
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Backend pull request #42
Opened 2022-04-12 14:25 UTC by RcleydsonR

## Descrição

Adição do endpoint de DETAIL do histórico de um talhão

## Está consertando alguma issue aberta?

- [#182](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/182)

## Tarefas gerais realizadas
- Adição do endpoint de DETAIL
- Adição de testes

2022-04-12 14:53 UTC, Joao-Moura approved these changes
Não entendi pq mudou o nome do serializer, mas é isso. Parabéns.
![](https://tenor.com/view/epico-cat-epico-cat-epic-cat-meme-epic-cat-epico-meme-gif-20299736.gif)

2022-04-12 15:08 UTC, thiagohdaqw requested changes

2022-04-12 15:08 UTC, thiagohdaqw commented on talhao/urls.py
> +            r'^(?P<idTalhao>{})/historico/plantio/$'.format(UUID4_URL),
```suggestion
            r'^(?P<idTalhao>{})/$'.format(UUID4_URL),
```
Se é um detail de talhão, com detalhamento de suas informações e plantios, não faz sentido ficar em uma rota /historico/plantios, pois não é retornado apenas os plantios do talhão. Seguir o proprio padrão no rest nesse caso é mais adequado

2022-04-12 20:53 UTC, RcleydsonR commented on talhao/urls.py
> +            r'^(?P<idTalhao>{})/historico/plantio/$'.format(UUID4_URL),
Na realidade, o correto no detail do talhão é retornar somente o plantio que está ativo, porém esse histórico retornaria todos os plantios que já aconteceram, não temos a rota de detail porque já está sendo recebido tudo pela propriedade, se houver a necessidade dessa rota de detail do talhão eu poderia fazer, mas será que tem mesmo ?

2022-04-12 20:57 UTC, thiagohdaqw commented on talhao/urls.py
> +            r'^(?P<idTalhao>{})/historico/plantio/$'.format(UUID4_URL),
Na realidade, no detalhe de talhao deveria retornar todos os plantios, visto que é o detalhe dele. A rota /historico/plantios está agindo como o detail porque oq é retornado não é apenas plantios é todo o detalhe do talhao.

2022-04-13 00:23 UTC, RcleydsonR commented on talhao/urls.py
> +            r'^(?P<idTalhao>{})/historico/plantio/$'.format(UUID4_URL),
Ok, seu comentário faz sentido, estarei aplicando a mudança necessária.

2022-04-13 00:23 UTC, RcleydsonR commented on talhao/urls.py
> +            r'^(?P<idTalhao>{})/historico/plantio/$'.format(UUID4_URL),
Fixed

2022-04-13 00:31 UTC, thiagohdaqw approved these changes
show de bola

2022-04-13 00:51 UTC, merged